// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/google/transit/gtfs-realtime-LIRR.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct TransitRealtime_MtaStopTimeUpdate {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension TransitRealtime_MtaStopTimeUpdate: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Extension support defined in gtfs-realtime-LIRR.proto.

// MARK: - Extension Properties

// Swift Extensions on the exteneded Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension TransitRealtime_TripUpdate.StopTimeUpdate {

  ///can add additional fields here without having to extend StopTimeUpdate again
  var TransitRealtime_MtaStopTimeUpdate_track: String {
    get {return getExtensionValue(ext: TransitRealtime_MtaStopTimeUpdate.Extensions.track) ?? String()}
    set {setExtensionValue(ext: TransitRealtime_MtaStopTimeUpdate.Extensions.track, value: newValue)}
  }
  /// Returns true if extension `TransitRealtime_MtaStopTimeUpdate.Extensions.track`
  /// has been explicitly set.
  var hasTransitRealtime_MtaStopTimeUpdate_track: Bool {
    return hasExtensionValue(ext: TransitRealtime_MtaStopTimeUpdate.Extensions.track)
  }
  /// Clears the value of extension `TransitRealtime_MtaStopTimeUpdate.Extensions.track`.
  /// Subsequent reads from it will return its default value.
  mutating func clearTransitRealtime_MtaStopTimeUpdate_track() {
    clearExtensionValue(ext: TransitRealtime_MtaStopTimeUpdate.Extensions.track)
  }

}

// MARK: - File's ExtensionMap: TransitRealtime_Gtfs_u45Realtime_u45Lirr_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
let TransitRealtime_Gtfs_u45Realtime_u45Lirr_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  TransitRealtime_MtaStopTimeUpdate.Extensions.track
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

extension TransitRealtime_MtaStopTimeUpdate {
  enum Extensions {
    ///can add additional fields here without having to extend StopTimeUpdate again
    static let track = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, TransitRealtime_TripUpdate.StopTimeUpdate>(
      _protobuf_fieldNumber: 1005,
      fieldName: "transit_realtime.MtaStopTimeUpdate.track"
    )
  }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "transit_realtime"

extension TransitRealtime_MtaStopTimeUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MtaStopTimeUpdate"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TransitRealtime_MtaStopTimeUpdate, rhs: TransitRealtime_MtaStopTimeUpdate) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
